### ISSUE TITLE
我想自己添加角色的时候，他旁白就一直是我刚开始预设的那句，怎么办

### ISSUE THREAD

**Issue by qihangf** [shengxia/RWKV_Role_Playing#10]
同上

**Comment by shengxia** [comment]
这个多重试几次吧，我也经常发现会重复，我也没找到什么好办法，让我再多研究研究或者再等等新的模型，看看有没有什么好办法能解决。

**Comment by shengxia** [comment]
我最近更新了一下dev分支版，你要不试试那个，这个版本使用了新的模型，也增加了一个生成多次的参数配置，可以让AI的回复变得更长，你试试看是否回复的长一些就不太容易让旁白重复了。

**Comment by qihangf** [comment]
谢谢大佬
