### ISSUE TITLE
减少“载入角色”和“清除上一条”的开销

### ISSUE THREAD

**Issue by azige** [shengxia/RWKV_Role_Playing#19]
我发现标题所述的两个操作会造成跟生成新内容一样的开销，但实际上不会有任何新内容被生成，而使用“清空聊天”的时候却没有任何开销马上就能完成。
我尝试过改进这个问题，但是因为对代码库理解得不深而且不熟悉 python 所以效果不好，具体可以参考这里：<https://github.com/shengxia/RWKV_Role_Playing/compare/master...azige:RWKV_Role_Playing:master>
简单的说思路就是设置一个标记，如果用户进行过“载入角色”、“清除上一条”、“清空聊天”的操作，则在下一次生成内容的时候把旧的状态丢弃掉从头开始重新生成，否则就在上一次生成的状态的基础上继续生成。这样就不会有不必要的额外开销，全部集中到真正需要生成内容的时候。

**Comment by shengxia** [comment]
是这样的，我这里用了一个公共参数all_state保存各个状态，一个是载入角色后的状态（chat_init），一个是上一次的状态（chat_pre），该状态主要是为了重说这个功能用的，还有一个就是当前的状态（chat），清空聊天时之所以没有任何开销，就是因为我直接把chat_pre给删了，然后把chat_init复制到chat里面，从而完成了重载。
载入角色和清空聊天这两个总得有一个有开销，目前我只是把这个开销放在了载入角色中，事实上，我也完全可以不这么做，也就是说，我把chat_init也保存在sav文件中，我以前这么做过，但是这样的sav文件会很大，毕竟大家现在都用固态硬盘了，我为了节省点儿硬盘寿命就给删了。
至于清除上一条，其实是有办法减少开销的，比如我把chat_pre直接复制到chat里面，然后把chat_pre删了就行了，只不过这样做会导致我只能清除一次，而且清除完之后，也没办法让模型重说了，所以我目前做的是，先把chat_pre复制给chat，然后把历史记录给拼起来然后让模型生成一遍chat_pre的状态，这就是清除上一条开销巨大的原因。

**Comment by azige** [comment]
我的观点是重新组织一下代码，把需要较大开销的工作放到实际生成新内容的时候。考虑以下场景

- 多次载入不同的角色，查看聊天历史记录。
- 多次清除上一条，让对话回滚到更早的状态。

现在用户在进行以上行为的时候不得不忍受巨大开销，而实际上这些开销完全是不必要的。

我的版本基本实现了我想要的效果，但是因为之前我没有理解你是如何管理状态的所以制造了一些额外的 bug，所以我觉得这些代码还是得你来重构可能会更好。

**Comment by shengxia** [comment]
你说的回滚的逻辑是不是这样的？
比如我想回滚4条对话，我点四次“清除上一条”，此时我给这要清除的四条都标记成为“待清除”，并且在前端把这四条对话都给删掉，当用户再次聊的时候，我把新的聊天内容给拼上，生成一份新的聊天内容，我调用两次模型，生成新的chat和chat_pre，这样就不用像现在一样调用8次模型了。

**Comment by azige** [comment]
差不多如此，如果你有意愿重构这个项目的代码的话可以考虑参考我的代码，如果不打算改了也无妨，取决于你。我之前尝试解决问题的时候想把 `chat_init` 状态完全丢弃掉，但是当时我也不清楚这是否合适，而且我不熟悉 python，没有能力和精力维护 fork，最近身边的人也不玩这个项目了，所以就把问题留给你了。

**Comment by shengxia** [comment]
没问题，这事儿反正我记下来了，这段时间再写那个api，也有了一些新的灵感，等回头那边那个项目稳定了，也把这个给弄上。

**Comment by shengxia** [comment]
我这边重新整理了一下各种载入逻辑，你可以拉一下最新的dev版，看看是不是好了一些。
