### ISSUE TITLE
怎么调整回答字数啊

### ISSUE THREAD

**Issue by amberfay** [shengxia/RWKV_Role_Playing#2]
猫娘每次回答字数很少，冒险的回答字数也不多，回答字数的参数可以在哪里设置啊

**Comment by amberfay** [comment]
我试过在初始设置里 加入设定，好像不是很好用

**Comment by shengxia** [comment]
> 我试过在初始设置里 加入设定，好像不是很好用

我确定了，是修改CHAT_LEN_SHORT和CHAT_LEN_LONG，把这两个值增大，能够增加生成数量，尤其是指令模式，使用目前最新的v10模型，生成文本的字数会有所提高，当然了，在角色扮演模式下，ai肯定是不会给你写小作文的。
