### ISSUE TITLE
跑题严重

### ISSUE THREAD

**Issue by Sincejunly** [shengxia/RWKV_Role_Playing#3]
不管是聊天，还是冒险，跑题都好严重，我是一张2080ti显卡跑RWKV-4-Raven-7B-v6-EngChnJpn-20230331-ctx4096
有什么办法能优化一下？感觉达不到作者演示的效果

**Comment by Sincejunly** [comment]
讲的话也没啥逻辑，有的时候还会自己生成主人的对话，有法子控制一下吗

**Comment by Sincejunly** [comment]
才留意到EN开头我还以为7B全是中文主导 ，我再试试罢

**Comment by shengxia** [comment]
嗯，这东西我也是三天两头改，我也没找到啥稳定的方法，虽然我想甩锅给模型的参数量还不够。

**Comment by shengxia** [comment]
好吧，是我写错了一个函数，导致token没加载对，已修复。

**Comment by Sincejunly** [comment]
今天下了新版，出了一大堆日志

**Comment by Sincejunly** [comment]
```
D:\Anaconda3\envs\ChatRWKV\lib\site-packages\torch\include\c10/util/Optional.h(212): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构函数隐式定义为“已删除”
        with
        [
            T=at::TensorBase
        ]
D:\Anaconda3\envs\ChatRWKV\lib\site-packages\torch\include\c10/util/Optional.h(411): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用
        with
        [
            T=at::TensorBase
        ]
```
差不多是这种出了几百行 太多了

**Comment by Sincejunly** [comment]
![image](https://user-images.githubusercontent.com/96775034/232101475-d7a55257-672e-4b00-8e47-3ee6acbc700a.png)
啊这 @shengxia

**Comment by Sincejunly** [comment]
笑出猪叫
![image](https://user-images.githubusercontent.com/96775034/232102096-0d79aeb8-dc42-43c7-a3e9-5ffe371c9858.png)

**Comment by shengxia** [comment]
> ```
> D:\Anaconda3\envs\ChatRWKV\lib\site-packages\torch\include\c10/util/Optional.h(212): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构函数隐式定义为“已删除”
>         with
>         [
>             T=at::TensorBase
>         ]
> D:\Anaconda3\envs\ChatRWKV\lib\site-packages\torch\include\c10/util/Optional.h(411): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用
>         with
>         [
>             T=at::TensorBase
>         ]
> ```
> 
> 差不多是这种出了几百行 太多了

貌似这个是在编译cuda内核，可以不用管他，最后会跑起来。

**Comment by BlinkDL** [comment]
> 不管是聊天，还是冒险，跑题都好严重，我是一张2080ti显卡跑RWKV-4-Raven-7B-v6-EngChnJpn-20230331-ctx4096 有什么办法能优化一下？感觉达不到作者演示的效果

现在 Raven 7B 已经 v9x 了，请看 https://huggingface.co/BlinkDL/rwkv-4-raven
