### ISSUE TITLE
大佬可以帮我看看这个是怎么回事吗

### ISSUE THREAD

**Issue by HuXinjing** [shengxia/RWKV_Role_Playing#31]
blocks.31.ln1.weight              f16   cuda:0   2560
blocks.31.ln1.bias                f16   cuda:0   2560
blocks.31.ln2.weight              f16   cuda:0   2560
blocks.31.ln2.bias                f16   cuda:0   2560
blocks.31.att.time_decay          f32   cuda:0   2560
blocks.31.att.time_first          f32   cuda:0   2560
blocks.31.att.time_mix_k          f16   cuda:0   2560
blocks.31.att.time_mix_v          f16   cuda:0   2560
blocks.31.att.time_mix_r          f16   cuda:0   2560
blocks.31.att.key.weight          f16   cuda:0   2560  2560 
blocks.31.att.value.weight        f16   cuda:0   2560  2560 
blocks.31.att.receptance.weight   f16   cuda:0   2560  2560 
blocks.31.att.output.weight       f16   cuda:0   2560  2560 
blocks.31.ffn.time_mix_k          f16   cuda:0   2560       
blocks.31.ffn.time_mix_r          f16   cuda:0   2560
blocks.31.ffn.key.weight          f16   cuda:0   2560 10240 
blocks.31.ffn.receptance.weight   f16   cuda:0   2560  2560 
blocks.31.ffn.value.weight        f16   cuda:0  10240  2560 
ln_out.weight                     f16   cuda:0   2560       
ln_out.bias                       f16   cuda:0   2560
head.weight                       f16   cuda:0   2560 65536 
E:\anaconda3\envs\RWKV\Lib\site-packages\gradio\blocks.py:889: UserWarning: api_name __send_message
 already exists, using __send_message_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
E:\anaconda3\envs\RWKV\Lib\site-packages\gradio\blocks.py:889: UserWarning: api_name __arrange_toke
n already exists, using __arrange_token_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
E:\anaconda3\envs\RWKV\Lib\site-packages\gradio\blocks.py:889: UserWarning: api_name __send_message
 already exists, using __send_message_2
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
E:\anaconda3\envs\RWKV\Lib\site-packages\gradio\blocks.py:889: UserWarning: api_name __arrange_toke
n already exists, using __arrange_token_2
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
E:\anaconda3\envs\RWKV\Lib\site-packages\gradio\blocks.py:889: UserWarning: api_name __send_message
 already exists, using __send_message_3
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
E:\anaconda3\envs\RWKV\Lib\site-packages\gradio\blocks.py:889: UserWarning: api_name __arrange_toke
n already exists, using __arrange_token_3
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
Traceback (most recent call last):
  File "E:\codes\RWKV_Role_Playing\webui.py", line 27, in <module>
    app.queue(concurrency_count=5, max_size=64).launch(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\RWKV\Lib\site-packages\gradio\blocks.py", line 1635, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on ev
ent listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). 
If necessary, the total number of workers can be configured via `max_threads` in launch().
各种安完执行 python webui.py --listen就报上面的（model的默认路径已经改过了）

**Comment by shengxia** [comment]
看起来似乎是concurrency_count这个参数已经废弃了，你打开webui.py，然后给"concurrency_count=5, "这个给删了，然后再试试，gradio更新的挺快啊，好多参数都不能用了……

**Comment by shengxia** [comment]
emmmm，我试着把gradio更新到了最新，发现需要兼容的东西更多了，算了，我摆了，还是用老版本吧，反正这玩意儿也没啥功能，你这样，执行这个命令。
pip install gradio==3.46.0
稍后我会把requirements给更新了。

**Comment by HuXinjing** [comment]
3.46.0看起来能工作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月7日(星期二) 上午10:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shengxia/RWKV_Role_Playing] 大佬可以帮我看看这个是怎么回事吗 (Issue #31)





 
emmmm，我试着把gradio更新到了最新，发现需要兼容的东西更多了，算了，我摆了，还是用老版本吧，反正这玩意儿也没啥功能，你这样，执行这个命令。
 pip install gradio==3.46.0
 稍后我会把requirements给更新了。
