### ISSUE TITLE
【建议】加个彻底重置角色的选项

### ISSUE THREAD

**Issue by tjsky** [shengxia/RWKV_Role_Playing#35]
其实就是别人遇到的问题，
1、使用旧版代码玩过一段时间，建立了一个`角色A`保存。
2、pull到新版后，代码里的初始prompt被改了，
3、重新运行代码
4、直接在web里把`角色A`给【重置角色】。
5、角色设定会使用原来的初始sav文件状态，也就是角色的初始prompt还是旧代码生成出来的状态。

当然解决也很简单
1.随便改一下角色设定，再保存一次。可以生成新的初始sav文件
2、将角色文件夹内的对应的sav文件删除，重新生成。

不过我感觉还是做一个额外的重新生成初始sav的功能吧，可以放在【调试】标签页里？
因为不知道这个需求，是不是个“伪需求”，没直接提pull requests，大家看呢？

**Comment by shengxia** [comment]
我明白你的意思了，其实我自己在调试初始prompt的时候也经常碰到这个问题，不过我就是在载入角色后，进入角色选项卡里面，然后直接点击保存角色来达到完全重置角色的目的，我就算做这个功能，也就是相当于给保存角色这个按钮功能给加到调试标签页里面，老实讲有点儿多余，不如先这么凑活着？

**Comment by tjsky** [comment]
> 我明白你的意思了，其实我自己在调试初始prompt的时候也经常碰到这个问题，不过我就是在载入角色后，进入角色选项卡里面，然后直接点击保存角色来达到完全重置角色的目的，我就算做这个功能，也就是相当于给保存角色这个按钮功能给加到调试标签页里面，老实讲有点儿多余，不如先这么凑活着？

【直接点击保存角色来达到完全重置角色的目的】这个方式比较好。
