### ISSUE TITLE
纯小白用户提问

### ISSUE THREAD

**Issue by ZiSaAcZ7** [shengxia/RWKV_Role_Playing#39]
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "D:\RWKV_Role_Playing\runtime\Lib\site-packages\rwkv\model.py", line 867, in att_seq_v6_0

        xx = F.layer_norm(x, (x.shape[-1],), weight=ln_w, bias=ln_b)
        sx = torch.cat((sx.unsqueeze(0), xx[:-1,:])) - xx
             ~~~~~~~~~ <--- HERE
        xxx = xx + sx * x_maa
        xxx = torch.tanh(xxx @ tm_w1).view(T, 5, -1).transpose(0, 1)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2560 but got size 5120 for tensor number 1 in the list.
是什么意思？怎么解决？

**Comment by ZiSaAcZ7** [comment]
付费咨询了下，说是模型结构不一样

**Comment by shengxia** [comment]
哦，这个啊，这个可能是比如你用了7b的模型，但是载入了3b的存档，或者用了7b的存档，载入了3b的模型，总之就是模型和存档不一致。
