### ISSUE TITLE
请问是哪位群友做的，可以更新README说明最新是Raven v9x了（很快v10）

### ISSUE THREAD

**Issue by BlinkDL** [shengxia/RWKV_Role_Playing#5]
可以在README告诉大家 https://huggingface.co/BlinkDL/rwkv-4-raven 现在已经是 v9x 了，很快 v10

请问在 RWKV 技术QQ群吗，如果不在可以加一下，谢谢

**Comment by shengxia** [comment]
> 可以在README告诉大家 https://huggingface.co/BlinkDL/rwkv-4-raven 现在已经是 v9x 了，很快 v10
> 
> 请问在 RWKV 技术QQ群吗，如果不在可以加一下，谢谢

我在google colab里面用的模型就是v9x的。

**Comment by BlinkDL** [comment]
> 嗯，没问题，我过段时间把readme更新一下，我在那个553456870群里面。

好啊，请和我说句话谢谢，另外RWKV技术群325154699
