### ISSUE TITLE
浏览器经常报错

### ISSUE THREAD

**Issue by ge90114b** [shengxia/RWKV_Role_Playing#6]
![2Q6G}10L(}L8~)8G3WV%62U](https://user-images.githubusercontent.com/111622870/234594866-812ecbf3-1fa4-4222-bd7f-06295790e209.png)
如图，即使重启也会报错，是webui的问题吗

**Comment by shengxia** [comment]
这个错误是没办法访问到google cdn上的一些资源报的错误，我这边因为开着代理，所以没有报这样的错误，但是这样的错误影响webui的使用吗？

**Comment by ge90114b** [comment]
又来新问题了
动了一下sdwebui，忽然所有gradio的网页都报错这个，您写的ui点进去直接报错了
试过重新clone和重新安装gradio都没解决
![OY~SGMJ_A9B1%W1 7TBO@XA](https://user-images.githubusercontent.com/111622870/235765745-ff077fd1-38a4-4c5f-beab-0f9afec5afec.png)

**Comment by shengxia** [comment]
你方便说一下你现在用的gradio的版本吗？我看看会不会是版本兼容的问题。

**Comment by ge90114b** [comment]
3.28.1

**Comment by shengxia** [comment]
我这边尝试着把gradio更新到了和你一样的版本，但是并没有报这样的错误，能把控制台里面的错误信息发出来看看吗？

**Comment by shengxia** [comment]
对了，我想到可能还有个问题，就是sd那边最近把pytorch给更新到2.0了吧，这个项目依赖的pytorch是1.13，我不太确定会不会和这个也有关系。

**Comment by ge90114b** [comment]
又试了一下 莫名其妙好了😂昨晚关机今早开了试的
